In [1]:
import pandas as pd

In [49]:
genes = pd.read_csv('RNA-seq of TCGA-LUAD.csv',index_col='Unnamed: 0')

survive_and_time = pd.read_csv("survival of TCGA-LUAD.csv",index_col='Unnamed: 0')

In [50]:
genes.head()

,TCGA-69-7978-01,TCGA-62-8399-01,TCGA-78-7539-01,TCGA-73-4658-01,TCGA-44-6775-01,TCGA-44-2655-01,TCGA-44-3398-01,TCGA-62-8397-01,TCGA-53-A4EZ-01,TCGA-50-7109-01,...,TCGA-75-7025-01,TCGA-55-7726-01,TCGA-L9-A743-01,TCGA-86-8358-01,TCGA-55-6972-01,TCGA-55-7727-01,TCGA-91-6831-01,TCGA-MN-A4N4-01,TCGA-55-8302-01,TCGA-MP-A4TK-01
ARHGEF10L,9.9898,10.4257,9.6264,9.2078,10.0039,9.3263,9.0249,10.5411,10.8969,8.3280,...,10.0905,7.5219,9.6563,9.2042,8.2127,7.2428,8.8388,9.9341,10.1696,10.1272
HIF3A,4.2598,11.6239,9.1362,5.0288,4.0573,5.5335,5.7347,6.6477,8.0041,6.5878,...,8.0944,4.2952,5.1675,9.2442,9.0641,7.5416,3.5613,8.3457,5.5364,10.2122
RNF17,0.4181,0.0000,1.1231,0.0000,1.0069,0.6021,0.0000,0.0000,0.0000,0.0000,...,0.4628,0.0000,0.9593,0.7339,1.0987,0.9392,0.0000,0.9715,0.0000,0.5804
RNF10,10.3657,11.5489,11.6692,11.6209,11.1721,11.9169,11.3274,12.3611,12.3762,11.9017,...,11.3260,12.0388,11.4458,11.5642,11.5881,11.8686,12.2704,11.8150,11.7813,11.4430
RNF11,11.1718,11.0200,10.4679,11.3414,11.0969,11.4044,11.4975,11.2828,10.3068,10.5777,...,10.8121,11.3304,10.4473,10.9991,10.0014,11.2862,11.1187,10.6101,10.5163,11.1243

In [51]:
#status: 0-dead, 1-survived
#os: is the time of life from the beginning of diagnosis until death

survive_and_time.head()

              status    os
TCGA-69-7978       0   134
TCGA-62-8399       0  2696
TCGA-78-7539       0   791
TCGA-73-4658       1  1600
TCGA-44-6775       0   705

In [52]:
genes.index.values

array(['ARHGEF10L', 'HIF3A', 'RNF17', ..., 'GSTK1', 'SELP', 'SELS'],
      dtype=object)

In [53]:
arr = ["STAT2", "STAT1", "JAK2", "STAT5A", "JAK1", "SRC", "E2F8", "E2F7", "E2F6", "E2F5", "E2F4", "E2F2", "E2F1", "CDKN2A",
            "CDKN2B", "CDK4", "MYC", "CCND1", "CDKN1B", "CCND2", "CDK6", "CDKN1A", "CDC25A", "CDK2", "CCNE1", "STAT3", "STAT5B",
            "E2F3", "CDK1", "CCNB1", "CCNA1", "RBL2", "RBL1", "RB1" ]

genes = genes[genes.index.isin(arr)]

genes.head()

,TCGA-69-7978-01,TCGA-62-8399-01,TCGA-78-7539-01,TCGA-73-4658-01,TCGA-44-6775-01,TCGA-44-2655-01,TCGA-44-3398-01,TCGA-62-8397-01,TCGA-53-A4EZ-01,TCGA-50-7109-01,...,TCGA-75-7025-01,TCGA-55-7726-01,TCGA-L9-A743-01,TCGA-86-8358-01,TCGA-55-6972-01,TCGA-55-7727-01,TCGA-91-6831-01,TCGA-MN-A4N4-01,TCGA-55-8302-01,TCGA-MP-A4TK-01
STAT3,12.9561,12.9048,12.5909,12.6713,13.0070,12.9116,12.4059,12.1316,11.8181,12.9387,...,12.6110,12.7989,12.8392,12.2043,12.7150,13.0409,12.9511,12.3942,12.5679,12.2019
CDKN1B,10.1500,9.8010,9.6813,10.5813,10.0479,9.9863,10.5245,10.2715,9.8182,10.9243,...,10.7724,10.3295,10.7239,10.4390,11.1275,10.4895,11.0698,10.7927,10.8255,10.5737
CDKN1A,10.9259,12.1576,11.5231,12.5573,12.2415,12.0991,12.7652,10.6721,8.8896,10.9689,...,11.0696,11.9798,12.2754,11.5306,9.5395,9.8285,11.0342,11.8925,11.1700,11.5647
CCNA1,4.5768,2.5648,2.4378,2.4862,2.3330,4.2576,7.8137,3.4879,0.4786,0.6872,...,5.9865,3.7466,5.6468,6.6217,3.1685,0.0000,2.0310,3.5910,1.4122,4.4788
E2F7,5.7493,6.4405,3.6424,4.4405,6.9503,3.7750,5.4108,3.4879,5.5676,9.2741,...,5.6703,8.4279,6.0478,8.5910,2.1456,5.6853,6.0406,5.3701,6.0520,7.4294

In [54]:
genes = genes.T

genes['type_sample'] = [id.split('-')[-1] for id in genes.index.values]
genes.index = ['-'.join(id.split('-')[:-1]) for id in genes.index.values]

genes.head()

,STAT3,CDKN1B,CDKN1A,CCNA1,E2F7,E2F6,E2F5,E2F4,E2F3,E2F2,...,MYC,CCND1,CCND2,JAK2,JAK1,RBL1,RB1,STAT2,STAT1,type_sample
TCGA-69-7978,12.9561,10.1500,10.9259,4.5768,5.7493,7.6659,7.4870,10.7342,9.2285,6.4331,...,11.3412,13.0935,9.9831,9.6474,12.7796,8.3803,9.7211,11.5004,14.1191,01
TCGA-62-8399,12.9048,9.8010,12.1576,2.5648,6.4405,8.9665,8.0528,10.6968,10.6323,8.4976,...,10.2392,12.3969,8.1493,7.0262,11.9003,7.8656,9.6027,12.1604,12.6398,01
TCGA-78-7539,12.5909,9.6813,11.5231,2.4378,3.6424,8.6923,7.2938,10.2176,9.4260,5.4204,...,10.3997,12.9586,11.7367,8.3032,11.7045,6.9488,9.5805,11.4269,13.7554,01
TCGA-73-4658,12.6713,10.5813,12.5573,2.4862,4.4405,8.1296,7.6506,10.0596,9.4679,6.4669,...,11.1295,13.0687,10.1175,8.4546,12.2850,7.4349,10.3898,10.9871,12.1910,01
TCGA-44-6775,13.0070,10.0479,12.2415,2.3330,6.9503,8.6773,6.4305,9.8000,9.2711,7.7983,...,9.5827,11.7717,10.0547,9.1469,12.2651,8.3996,9.2887,11.3776,12.5364,01

In [60]:
data = pd.merge(genes,survive_and_time,how='inner',left_on=genes.index,right_on=survive_and_time.index)
data.rename(columns={"key_0":"id","os":"os_days","status":"survived"},inplace=True)
data.head()

,id,STAT3,CDKN1B,CDKN1A,CCNA1,E2F7,E2F6,E2F5,E2F4,E2F3,...,CCND2,JAK2,JAK1,RBL1,RB1,STAT2,STAT1,type_sample,survived,os_days
0,TCGA-69-7978,12.9561,10.1500,10.9259,4.5768,5.7493,7.6659,7.4870,10.7342,9.2285,...,9.9831,9.6474,12.7796,8.3803,9.7211,11.5004,14.1191,01,0,134
1,TCGA-62-8399,12.9048,9.8010,12.1576,2.5648,6.4405,8.9665,8.0528,10.6968,10.6323,...,8.1493,7.0262,11.9003,7.8656,9.6027,12.1604,12.6398,01,0,2696
2,TCGA-78-7539,12.5909,9.6813,11.5231,2.4378,3.6424,8.6923,7.2938,10.2176,9.4260,...,11.7367,8.3032,11.7045,6.9488,9.5805,11.4269,13.7554,01,0,791
3,TCGA-73-4658,12.6713,10.5813,12.5573,2.4862,4.4405,8.1296,7.6506,10.0596,9.4679,...,10.1175,8.4546,12.2850,7.4349,10.3898,10.9871,12.1910,01,1,1600
4,TCGA-44-6775,13.0070,10.0479,12.2415,2.3330,6.9503,8.6773,6.4305,9.8000,9.2711,...,10.0547,9.1469,12.2651,8.3996,9.2887,11.3776,12.5364,01,0,705

In [63]:
data.to_csv('new_genes_data',index=False)